import type { AppLocale } from "./locale.js";
import type {
  Accessibility,
  AgeGroup,
  Allergy,
  ChargePort,
  DietCondition,
  FuelType,
  Language,
  NationalityCode,
  ParkingPrivilege,
  Transport,
  TravelType,
  VegetarianLevel,
} from "./profile.js";

export type UiCopy = {
  app: {
    title: string;
    subtitle: string;
    chats: string;
    routes: string;
    newChat: string;
    settings: string; // 내정보 (프로필)
    empty: string;
    placeholder: string;
    listening: string;
    send: string;
    stop: string;
    copy: string;
    copied: string;
    edit: string;
    cancel: string;
    like: string;
    dislike: string;
    saveRoute: (n: number) => string;
    savedRoute: string;
    routeSaved: string;
    routeSaveFail: string;
    thinking: string;
    stopping: string;
    truncating: string;
    attachPhoto: string;
    photoLimit: (n: number) => string;
    photoLimitPartial: (n: number) => string;
    feedbackThanks: string;
    feedbackFail: string;
    retractFail: string;
    editMeta: string;
    editMetaPhotos: (n: number) => string;
    stopped: string;
    reasonTitle: string;
    reasonPlaceholder: string;
    close: string;
    reasons: string[];
    missingKey: string;
  };
  suggestions: string[];
  /** suggestions 배열에서 기상청 예보로 바뀌는 칩 위치 */
  weatherSuggestionIndex: number;
  profile: {
    title: string;
    desc1: string;
    desc2: string;
    later: string;
    save: string;
    language: string;
    otherLangHint: string;
    nationality: string;
    nationalityPlaceholder: string;
    nationalityClear: string;
    nationalityEmpty: string;
    ageGroup: string;
    transport: string;
    transportHint: string;
    fuel: string;
    chargePorts: string;
    parkingPrivilege: string;
    parkingPrivilegeHint: string;
    travelTypes: string;
    travelHint: string;
    valuePref: string;
    valueForMoney: string;
    valueHeart: string;
    valueFlex: string;
    placePref: string;
    indoor: string;
    mid: string;
    outdoor: string;
    access: string;
    accessHint: string;
    diet: string;
    dietHint: string;
    vegNone: string;
    wheatFree: string;
    conditionHint: string;
    allergyHint: string;
    transports: Record<Transport, string>;
    fuels: Record<FuelType, string>;
    charges: Record<ChargePort, string>;
    parkingPrivileges: Record<ParkingPrivilege, string>;
    travels: Record<TravelType, string>;
    accessOpts: Record<Accessibility, { label: string; hint: string }>;
    veg: Record<VegetarianLevel, string>;
    conditions: Record<DietCondition, string>;
    allergies: Record<Allergy, string>;
    nationalities: Record<NationalityCode, string>;
    ageGroups: Record<AgeGroup, string>;
    languages: Record<Language, string>;
  };
  library: {
    label: string;
    chats: string;
    routes: string;
    close: string;
    note: string;
    emptyRoutes: string;
    emptyFavoriteRoutes: string;
    /** 경로 목록 필터 */
    allRoutes: string;
    favoriteRoutes: string;
    /** 경로 카드의 별 버튼 */
    addFavorite: string;
    removeFavorite: string;
    showOnMap: string;
    emptyChats: string;
    search: string;
    delete: string;
    export: string;
    rename: string;
    use: string;
    openChat: string;
  };
  mode: Record<"candidate" | "route" | "faq" | "report", string>;
  tool: {
    thinking: string;
    running: (name: string) => string;
    labels: Record<string, string>;
  };
};

const ko: UiCopy = {
  app: {
    title: "제주 복합경로 안내",
    subtitle: "관광지·맛집·주차장·충전소 12,368곳을 모아 두었습니다",
    chats: "대화 목록",
    routes: "저장한 경로",
    newChat: "새 대화",
    settings: "내정보",
    empty: "무엇을 도와드릴까요?",
    placeholder: "무엇이든 물어보세요",
    listening: "듣는 중… 끝나면 마이크를 다시 누르세요",
    send: "보내기",
    stop: "멈춤",
    copy: "복사",
    copied: "복사됨",
    edit: "수정",
    cancel: "취소",
    like: "좋아요",
    dislike: "싫어요",
    saveRoute: (n) => `이 경로 저장 (${n}곳)`,
    savedRoute: "저장된 경로 보기",
    routeSaved: "경로를 저장했습니다.",
    routeSaveFail: "저장 공간이 부족해 경로를 저장하지 못했습니다.",
    thinking: "생각하는 중",
    stopping: "멈추는 중",
    truncating: "이전 답변을 지우는 중",
    attachPhoto: "사진 첨부",
    photoLimit: (n) => `사진은 한 번에 ${n}장까지 보낼 수 있습니다.`,
    photoLimitPartial: (n) => `사진은 한 번에 제한되어 ${n}장만 붙였습니다.`,
    feedbackThanks: "의견을 보냈습니다. 고맙습니다.",
    feedbackFail: "평가를 보내지 못했습니다. 잠시 후 다시 눌러 주세요.",
    retractFail: "서버 기록을 정리하지 못해 질문을 남겨 두었습니다.",
    editMeta: "보내면 이 질문 뒤의 대화는 지워지고 새 답을 받습니다.",
    editMetaPhotos: (n) => ` 첨부한 사진 ${n}장도 함께 보냅니다.`,
    stopped: "응답을 멈췄습니다",
    reasonTitle: "어떤 점이 아쉬웠나요? (선택)",
    reasonPlaceholder: "자세히 적어 주시면 고치는 데 도움이 됩니다",
    close: "닫기",
    reasons: ["틀린 정보", "질문과 안 맞음", "너무 길거나 복잡함", "장소를 못 찾음"],
    missingKey:
      "VITE_API_KEY 가 설정되지 않았습니다.\nchat/web/.env.local.example 을 .env.local 로 복사하고 키를 채운 뒤\ndev 서버를 다시 시작하세요.",
  },
  suggestions: [
    "제주공항에서 동문시장 가는 방법 비교해 줘",
    "버스랑 택시 섞어서 성산일출봉 가는 법",
    "내일 날씨에 맞는 일정",
    "휠체어로 제주시청까지 가는 경로 알려줘",
    "차 없이 협재해수욕장 가장 빨리 가는 법",
  ],
  weatherSuggestionIndex: 2,
  profile: {
    title: "내정보",
    desc1: "선택하신 내용은 이 브라우저에만 저장되며, 추천에 참고합니다. 비워 두셔도 됩니다.",
    desc2: "내정보에서 수정하실 수 있습니다.",
    later: "나중에",
    save: "저장하고 시작",
    language: "언어",
    otherLangHint: "선택지에 없는 언어는 영어로 번역됩니다",
    nationality: "국적",
    nationalityPlaceholder: "선택해 주세요",
    nationalityClear: "국적 선택 해제",
    nationalityEmpty: "검색 결과가 없습니다",
    ageGroup: "나이대",
    transport: "이동수단",
    transportHint: "이용할 수단을 모두 골라 주세요 (복수 선택)",
    fuel: "차량 연료",
    chargePorts: "충전구 (복수 선택)",
    parkingPrivilege: "주차 우대",
    parkingPrivilegeHint: "해당되는 감면·전용 대상을 골라 주세요 (복수 선택 · 전기차는 연료에서 선택)",
    travelTypes: "여행 유형",
    travelHint: "관심 있는 유형을 골라 주세요 (복수 선택)",
    valuePref: "소비유형",
    valueForMoney: "가성비",
    valueHeart: "가심비",
    valueFlex: "flex",
    placePref: "실내 / 실외",
    indoor: "실내 선호",
    mid: "중간",
    outdoor: "실외 선호",
    access: "배리어프리",
    accessHint: "필요하신 편의시설 유형 (복수 선택)",
    diet: "식이",
    dietHint: "채식 정도 · 밀가루 · 할랄 · 질환 등",
    vegNone: "채식 해당 없음",
    wheatFree: "밀가루 제한",
    conditionHint: "식이 질환 (복수 선택 · 병명만 저장)",
    allergyHint: "알레르기 (식약처 표시 기준 19종 · 복수 선택)",
    transports: {
      walk: "도보",
      taxi: "택시",
      bus: "버스",
      car: "차량",
      shared_bike: "공유 킥보드/자전거",
    },
    fuels: { gasoline_diesel: "휘발유/디젤", lpg: "LPG", ev: "전기차" },
    charges: {
      dc_combo: "DC콤보",
      ac_slow: "완속",
      nacs: "NACS",
      ac_3phase: "AC3상",
      dc_chademo: "차데모",
    },
    parkingPrivileges: {
      compact: "경차",
      disabled: "장애인",
      veteran: "국가유공자",
      pregnant: "임산부",
      multi_child: "다자녀",
    },
    travels: {
      food: "음식",
      shopping: "쇼핑",
      experience: "체험",
      culture: "문화·역사",
      nature: "자연·휴양",
    },
    accessOpts: {
      infant: { label: "영유아", hint: "유모차·수유실·유아의자 등" },
      pet: { label: "반려동물", hint: "반려견·동반 가능 장소" },
      mobility: { label: "지체", hint: "주차·휠체어·엘리베이터 등" },
      visual: { label: "시각", hint: "점자·안내요원·오디오가이드 등" },
      hearing: { label: "청각", hint: "수화·자막 안내 등" },
    },
    veg: { flexitarian: "플렉시테리언", lacto_ovo: "락토오보", vegan: "비건" },
    conditions: {
      diabetes: "당뇨병",
      hypertension: "고혈압",
      kidney: "신장질환",
      hyperlipidemia: "고지혈증",
      gout: "통풍",
      fatty_liver: "지방간",
    },
    allergies: {
      egg: "난류(계란)",
      milk: "우유",
      buckwheat: "메밀",
      peanut: "땅콩",
      soy: "대두",
      wheat: "밀",
      mackerel: "고등어",
      crab: "게",
      shrimp: "새우",
      pork: "돼지고기",
      peach: "복숭아",
      tomato: "토마토",
      sulfite: "아황산류",
      walnut: "호두",
      chicken: "닭고기",
      beef: "쇠고기",
      squid: "오징어",
      shellfish: "조개류(굴·전복·홍합)",
      pine_nut: "잣",
    },
    nationalities: {
      KR: "대한민국",
      CN: "중국",
      JP: "일본",
      TW: "대만",
      HK: "홍콩",
      US: "미국",
      SG: "싱가포르",
      TH: "태국",
      VN: "베트남",
      MY: "말레이시아",
      ID: "인도네시아",
      PH: "필리핀",
      GB: "영국",
      DE: "독일",
      FR: "프랑스",
      AU: "호주",
      CA: "캐나다",
      RU: "러시아",
      IN: "인도",
      MN: "몽골",
      OTHER: "기타",
    },
    ageGroups: {
      "10s": "10대",
      "20s": "20대",
      "30s": "30대",
      "40s": "40대",
      "50s": "50대",
      "60plus": "60+",
    },
    languages: { ko: "한국어", zh: "中文", en: "English", ja: "日本語", other: "기타" },
  },
  library: {
    label: "보관함",
    chats: "대화",
    routes: "저장한 경로",
    close: "닫기",
    note: "이 브라우저에만 보관됩니다. 사이트 데이터를 지우면 사라집니다.",
    emptyRoutes: "저장한 경로가 없습니다.",
    emptyFavoriteRoutes: "즐겨찾기한 경로가 없습니다.",
    allRoutes: "전체",
    favoriteRoutes: "즐겨찾기",
    addFavorite: "즐겨찾기에 추가",
    removeFavorite: "즐겨찾기 해제",
    showOnMap: "지도에서 보기",
    emptyChats: "대화가 없습니다.",
    search: "검색",
    delete: "삭제",
    export: "내보내기",
    rename: "이름 바꾸기",
    use: "사용",
    openChat: "대화 열기",
  },
  mode: { candidate: "후보 선택", route: "길찾기", faq: "FAQ", report: "오류 제보" },
  tool: {
    thinking: "생각하는 중",
    running: (name) => `${name} 실행 중`,
    labels: {
      "kakao-search-places": "카카오맵에서 장소를 찾는 중",
      kakaoSearchPlaces: "카카오맵에서 장소를 찾는 중",
      "kakao-directions": "카카오 경로를 조회하는 중",
      kakaoDirections: "카카오 경로를 조회하는 중",
      "compare-directions": "이동수단별 경로를 비교하는 중",
      compareDirections: "이동수단별 경로를 비교하는 중",
      "search-places": "장소를 찾는 중",
      searchPlaces: "장소를 찾는 중",
      "search-downtown-stores": "원도심 매장을 찾는 중",
      searchDowntownStores: "원도심 매장을 찾는 중",
      "nearby-places": "근처를 둘러보는 중",
      nearbyPlaces: "근처를 둘러보는 중",
      "place-detail": "상세 정보를 확인하는 중",
      placeDetail: "상세 정보를 확인하는 중",
      "check-metric": "혼잡도·여석을 확인하는 중",
      checkMetric: "혼잡도·여석을 확인하는 중",
      "get-weather": "날씨를 확인하는 중",
      getWeather: "날씨를 확인하는 중",
      "naver-map-link": "길찾기 링크를 만드는 중",
      naverMapLink: "길찾기 링크를 만드는 중",
      "search-faq": "안내 FAQ 를 찾는 중",
      searchFaq: "안내 FAQ 를 찾는 중",
      "report-issue": "제보를 접수하는 중",
      reportIssue: "제보를 접수하는 중",
      "plan-visit-order": "방문순서를 짜는 중",
      planVisitOrder: "방문순서를 짜는 중",
    },
  },
};

const en: UiCopy = {
  app: {
    title: "Jeju Multimodal Route Guide",
    subtitle: "12,368 spots — sights, food, parking, and EV chargers",
    chats: "Chats",
    routes: "Saved routes",
    newChat: "New chat",
    settings: "My info",
    empty: "How can I help?",
    placeholder: "Ask anything",
    listening: "Listening… tap the mic again when done",
    send: "Send",
    stop: "Stop",
    copy: "Copy",
    copied: "Copied",
    edit: "Edit",
    cancel: "Cancel",
    like: "Like",
    dislike: "Dislike",
    saveRoute: (n) => `Save route (${n} stops)`,
    savedRoute: "View saved route",
    routeSaved: "Route saved.",
    routeSaveFail: "Not enough storage to save the route.",
    thinking: "Thinking",
    stopping: "Stopping",
    truncating: "Removing previous reply",
    attachPhoto: "Attach photo",
    photoLimit: (n) => `You can send up to ${n} photos at a time.`,
    photoLimitPartial: (n) => `Photo limit reached — attached ${n} only.`,
    feedbackThanks: "Thanks for your feedback.",
    feedbackFail: "Couldn't send feedback. Please try again.",
    retractFail: "Couldn't clear the server history, so the question was kept.",
    editMeta: "Sending will delete later messages and get a new reply.",
    editMetaPhotos: (n) => ` ${n} attached photo(s) will be sent again.`,
    stopped: "Response stopped",
    reasonTitle: "What went wrong? (optional)",
    reasonPlaceholder: "Details help us improve",
    close: "Close",
    reasons: ["Wrong info", "Off-topic", "Too long or complex", "Couldn't find a place"],
    missingKey:
      "VITE_API_KEY is not set.\nCopy chat/web/.env.local.example to .env.local, add the key,\nand restart the dev server.",
  },
  suggestions: [
    "Compare ways from Jeju Airport to Dongmun Market",
    "Bus + taxi route to Seongsan Ilchulbong",
    "A plan that fits tomorrow's weather",
    "Wheelchair-accessible route to Jeju City Hall",
    "Fastest way to Hyeopjae Beach without a car",
  ],
  weatherSuggestionIndex: 2,
  profile: {
    title: "My info",
    desc1: "Saved only in this browser and used for recommendations. You can leave fields empty.",
    desc2: "You can change them later in My info.",
    later: "Later",
    save: "Save & start",
    language: "Language",
    otherLangHint: "Unsupported languages are shown in English",
    nationality: "Nationality",
    nationalityPlaceholder: "Please select",
    nationalityClear: "Clear nationality",
    nationalityEmpty: "No results",
    ageGroup: "Age group",
    transport: "Transport",
    transportHint: "Select all that apply",
    fuel: "Vehicle fuel",
    chargePorts: "Charge ports (multiple)",
    parkingPrivilege: "Parking benefits",
    parkingPrivilegeHint: "Fee discounts or reserved spaces that apply (multiple · EV is under fuel)",
    travelTypes: "Travel interests",
    travelHint: "Select all that apply",
    valuePref: "Spending style",
    valueForMoney: "Value",
    valueHeart: "Treat",
    valueFlex: "Flex",
    placePref: "Indoor / Outdoor",
    indoor: "Prefer indoor",
    mid: "Neutral",
    outdoor: "Prefer outdoor",
    access: "Accessibility",
    accessHint: "Facility types you need (multiple)",
    diet: "Diet",
    dietHint: "Vegetarian level, wheat, halal, conditions, etc.",
    vegNone: "Not vegetarian",
    wheatFree: "Wheat-free",
    conditionHint: "Diet-related conditions (multiple · name only stored)",
    allergyHint: "Allergies (Korea MFDS 19 labels · multiple)",
    transports: {
      walk: "Walk",
      taxi: "Taxi",
      bus: "Bus",
      car: "Car",
      shared_bike: "Shared e-scooter / bike",
    },
    fuels: { gasoline_diesel: "Gas/Diesel", lpg: "LPG", ev: "EV" },
    charges: {
      dc_combo: "DC Combo",
      ac_slow: "AC slow",
      nacs: "NACS",
      ac_3phase: "AC 3-phase",
      dc_chademo: "CHAdeMO",
    },
    parkingPrivileges: {
      compact: "Compact car",
      disabled: "Disability",
      veteran: "National merit",
      pregnant: "Pregnant",
      multi_child: "Multi-child",
    },
    travels: {
      food: "Food",
      shopping: "Shopping",
      experience: "Experiences",
      culture: "Culture & history",
      nature: "Nature & rest",
    },
    accessOpts: {
      infant: { label: "Infants", hint: "Strollers, nursing rooms, high chairs" },
      pet: { label: "Pets", hint: "Pet-friendly places" },
      mobility: { label: "Mobility", hint: "Parking, wheelchairs, elevators" },
      visual: { label: "Visual", hint: "Braille, guides, audio guides" },
      hearing: { label: "Hearing", hint: "Sign language, captions" },
    },
    veg: { flexitarian: "Flexitarian", lacto_ovo: "Lacto-ovo", vegan: "Vegan" },
    conditions: {
      diabetes: "Diabetes",
      hypertension: "Hypertension",
      kidney: "Kidney disease",
      hyperlipidemia: "Hyperlipidemia",
      gout: "Gout",
      fatty_liver: "Fatty liver",
    },
    allergies: {
      egg: "Eggs",
      milk: "Milk",
      buckwheat: "Buckwheat",
      peanut: "Peanuts",
      soy: "Soy",
      wheat: "Wheat",
      mackerel: "Mackerel",
      crab: "Crab",
      shrimp: "Shrimp",
      pork: "Pork",
      peach: "Peach",
      tomato: "Tomato",
      sulfite: "Sulfites",
      walnut: "Walnut",
      chicken: "Chicken",
      beef: "Beef",
      squid: "Squid",
      shellfish: "Shellfish (oyster, abalone, mussel)",
      pine_nut: "Pine nut",
    },
    nationalities: {
      KR: "South Korea",
      CN: "China",
      JP: "Japan",
      TW: "Taiwan",
      HK: "Hong Kong",
      US: "United States",
      SG: "Singapore",
      TH: "Thailand",
      VN: "Vietnam",
      MY: "Malaysia",
      ID: "Indonesia",
      PH: "Philippines",
      GB: "United Kingdom",
      DE: "Germany",
      FR: "France",
      AU: "Australia",
      CA: "Canada",
      RU: "Russia",
      IN: "India",
      MN: "Mongolia",
      OTHER: "Other",
    },
    ageGroups: {
      "10s": "Teens",
      "20s": "20s",
      "30s": "30s",
      "40s": "40s",
      "50s": "50s",
      "60plus": "60+",
    },
    languages: { ko: "한국어", zh: "中文", en: "English", ja: "日本語", other: "Other" },
  },
  library: {
    label: "Library",
    chats: "Chats",
    routes: "Saved routes",
    close: "Close",
    note: "Stored only in this browser. Clearing site data removes them.",
    emptyRoutes: "No saved routes.",
    emptyFavoriteRoutes: "No favorite routes.",
    allRoutes: "All",
    favoriteRoutes: "Favorites",
    addFavorite: "Add to favorites",
    removeFavorite: "Remove from favorites",
    showOnMap: "Show on map",
    emptyChats: "No chats yet.",
    search: "Search",
    delete: "Delete",
    export: "Export",
    rename: "Rename",
    use: "Use",
    openChat: "Open chat",
  },
  mode: { candidate: "Suggestions", route: "Directions", faq: "FAQ", report: "Report" },
  tool: {
    thinking: "Thinking",
    running: (name) => `Running ${name}`,
    labels: {
      "kakao-search-places": "Searching Kakao Map",
      kakaoSearchPlaces: "Searching Kakao Map",
      "kakao-directions": "Getting Kakao directions",
      kakaoDirections: "Getting Kakao directions",
      "compare-directions": "Comparing travel modes",
      compareDirections: "Comparing travel modes",
      "search-places": "Searching places",
      searchPlaces: "Searching places",
      "search-downtown-stores": "Searching downtown stores",
      searchDowntownStores: "Searching downtown stores",
      "nearby-places": "Looking nearby",
      nearbyPlaces: "Looking nearby",
      "place-detail": "Checking details",
      placeDetail: "Checking details",
      "check-metric": "Checking crowding & availability",
      checkMetric: "Checking crowding & availability",
      "get-weather": "Checking weather",
      getWeather: "Checking weather",
      "naver-map-link": "Making map links",
      naverMapLink: "Making map links",
      "search-faq": "Searching FAQ",
      searchFaq: "Searching FAQ",
      "report-issue": "Submitting report",
      reportIssue: "Submitting report",
      "plan-visit-order": "Planning visit order",
      planVisitOrder: "Planning visit order",
    },
  },
};

const zh: UiCopy = {
  app: {
    title: "济州复合路线导航",
    subtitle: "已收录 12,368 处景点、美食、停车场与充电站",
    chats: "对话列表",
    routes: "已存路线",
    newChat: "新对话",
    settings: "我的信息",
    empty: "需要什么帮助？",
    placeholder: "随便问问",
    listening: "正在听… 结束后请再点一次麦克风",
    send: "发送",
    stop: "停止",
    copy: "复制",
    copied: "已复制",
    edit: "编辑",
    cancel: "取消",
    like: "赞",
    dislike: "踩",
    saveRoute: (n) => `保存路线（${n}处）`,
    savedRoute: "查看已存路线",
    routeSaved: "路线已保存。",
    routeSaveFail: "存储空间不足，未能保存路线。",
    thinking: "思考中",
    stopping: "正在停止",
    truncating: "正在删除上一轮回复",
    attachPhoto: "添加照片",
    photoLimit: (n) => `一次最多发送 ${n} 张照片。`,
    photoLimitPartial: (n) => `已达上限，仅添加了 ${n} 张。`,
    feedbackThanks: "已收到反馈，谢谢。",
    feedbackFail: "反馈发送失败，请稍后再试。",
    retractFail: "未能清理服务器记录，已保留该问题。",
    editMeta: "发送后将删除之后的对话并重新回答。",
    editMetaPhotos: (n) => ` 将一并发送 ${n} 张照片。`,
    stopped: "已停止回答",
    reasonTitle: "哪里不满意？（可选）",
    reasonPlaceholder: "详细说明有助于改进",
    close: "关闭",
    reasons: ["信息不对", "答非所问", "太长或太复杂", "找不到地点"],
    missingKey:
      "未设置 VITE_API_KEY。\n请将 chat/web/.env.local.example 复制为 .env.local 并填入密钥后\n重启开发服务器。",
  },
  suggestions: [
    "比较从济州机场到东门市场的交通方式",
    "公交加出租车去城山日出峰怎么走",
    "按明天天气安排行程",
    "坐轮椅去济州市厅的路线",
    "不开车最快怎么去挟才海水浴场",
  ],
  weatherSuggestionIndex: 2,
  profile: {
    title: "我的信息",
    desc1: "仅保存在本浏览器，用于推荐。也可以留空。",
    desc2: "之后可在「我的信息」中修改。",
    later: "稍后再说",
    save: "保存并开始",
    language: "语言",
    otherLangHint: "未列出的语言将以英语显示",
    nationality: "国籍",
    nationalityPlaceholder: "请选择",
    nationalityClear: "清除国籍",
    nationalityEmpty: "无搜索结果",
    ageGroup: "年龄段",
    transport: "交通方式",
    transportHint: "可多选",
    fuel: "车辆燃料",
    chargePorts: "充电接口（可多选）",
    parkingPrivilege: "停车优惠",
    parkingPrivilegeHint: "适用的减免·专用车位（可多选 · 电动车请在燃料中选择）",
    travelTypes: "旅行类型",
    travelHint: "可多选",
    valuePref: "消费类型",
    valueForMoney: "性价比",
    valueHeart: "悦己消费",
    valueFlex: "flex",
    placePref: "室内 / 室外",
    indoor: "偏室内",
    mid: "中立",
    outdoor: "偏室外",
    access: "无障碍",
    accessHint: "所需便利设施类型（可多选）",
    diet: "饮食",
    dietHint: "素食程度、面食、清真、相关疾病等",
    vegNone: "非素食",
    wheatFree: "忌面食",
    conditionHint: "饮食相关疾病（可多选 · 仅保存病名）",
    allergyHint: "过敏原（韩国食药处 19 项 · 可多选）",
    transports: {
      walk: "步行",
      taxi: "出租车",
      bus: "公交",
      car: "自驾",
      shared_bike: "共享滑板车/单车",
    },
    fuels: { gasoline_diesel: "汽油/柴油", lpg: "LPG", ev: "电动车" },
    charges: {
      dc_combo: "DC Combo",
      ac_slow: "慢充",
      nacs: "NACS",
      ac_3phase: "AC三相",
      dc_chademo: "CHAdeMO",
    },
    parkingPrivileges: {
      compact: "轻型车",
      disabled: "残疾人",
      veteran: "国家功勋",
      pregnant: "孕妇",
      multi_child: "多子女",
    },
    travels: {
      food: "美食",
      shopping: "购物",
      experience: "体验",
      culture: "文化历史",
      nature: "自然休闲",
    },
    accessOpts: {
      infant: { label: "婴幼儿", hint: "婴儿车、哺乳室、儿童椅等" },
      pet: { label: "宠物", hint: "可携宠场所" },
      mobility: { label: "肢体", hint: "停车、轮椅、电梯等" },
      visual: { label: "视觉", hint: "盲道、导览、语音导览等" },
      hearing: { label: "听觉", hint: "手语、字幕等" },
    },
    veg: { flexitarian: "弹性素食", lacto_ovo: "蛋奶素", vegan: "全素" },
    conditions: {
      diabetes: "糖尿病",
      hypertension: "高血压",
      kidney: "肾脏疾病",
      hyperlipidemia: "高血脂",
      gout: "痛风",
      fatty_liver: "脂肪肝",
    },
    allergies: {
      egg: "蛋类",
      milk: "牛奶",
      buckwheat: "荞麦",
      peanut: "花生",
      soy: "大豆",
      wheat: "小麦",
      mackerel: "鲭鱼",
      crab: "蟹",
      shrimp: "虾",
      pork: "猪肉",
      peach: "桃子",
      tomato: "番茄",
      sulfite: "亚硫酸盐",
      walnut: "核桃",
      chicken: "鸡肉",
      beef: "牛肉",
      squid: "鱿鱼",
      shellfish: "贝类（牡蛎·鲍鱼·贻贝）",
      pine_nut: "松子",
    },
    nationalities: {
      KR: "韩国",
      CN: "中国",
      JP: "日本",
      TW: "台湾",
      HK: "香港",
      US: "美国",
      SG: "新加坡",
      TH: "泰国",
      VN: "越南",
      MY: "马来西亚",
      ID: "印度尼西亚",
      PH: "菲律宾",
      GB: "英国",
      DE: "德国",
      FR: "法国",
      AU: "澳大利亚",
      CA: "加拿大",
      RU: "俄罗斯",
      IN: "印度",
      MN: "蒙古",
      OTHER: "其他",
    },
    ageGroups: {
      "10s": "10多岁",
      "20s": "20多岁",
      "30s": "30多岁",
      "40s": "40多岁",
      "50s": "50多岁",
      "60plus": "60+",
    },
    languages: { ko: "한국어", zh: "中文", en: "English", ja: "日本語", other: "其他" },
  },
  library: {
    label: "收藏夹",
    chats: "对话",
    routes: "已存路线",
    close: "关闭",
    note: "仅保存在本浏览器。清除网站数据后会消失。",
    emptyRoutes: "暂无已存路线。",
    emptyFavoriteRoutes: "暂无收藏的路线。",
    allRoutes: "全部",
    favoriteRoutes: "收藏",
    addFavorite: "加入收藏",
    removeFavorite: "取消收藏",
    showOnMap: "在地图上查看",
    emptyChats: "暂无对话。",
    search: "搜索",
    delete: "删除",
    export: "导出",
    rename: "重命名",
    use: "使用",
    openChat: "打开对话",
  },
  mode: { candidate: "候选推荐", route: "路线", faq: "FAQ", report: "报错" },
  tool: {
    thinking: "思考中",
    running: (name) => `正在执行 ${name}`,
    labels: {
      "kakao-search-places": "正在搜索 Kakao 地图",
      kakaoSearchPlaces: "正在搜索 Kakao 地图",
      "kakao-directions": "正在查询 Kakao 路线",
      kakaoDirections: "正在查询 Kakao 路线",
      "compare-directions": "正在比较出行方式",
      compareDirections: "正在比较出行方式",
      "search-places": "正在搜索地点",
      searchPlaces: "正在搜索地点",
      "search-downtown-stores": "正在搜索原都心店铺",
      searchDowntownStores: "正在搜索原都心店铺",
      "nearby-places": "正在查看附近",
      nearbyPlaces: "正在查看附近",
      "place-detail": "正在查看详情",
      placeDetail: "正在查看详情",
      "check-metric": "正在查看拥堵与空位",
      checkMetric: "正在查看拥堵与空位",
      "get-weather": "正在查看天气",
      getWeather: "正在查看天气",
      "naver-map-link": "正在生成导航链接",
      naverMapLink: "正在生成导航链接",
      "search-faq": "正在搜索 FAQ",
      searchFaq: "正在搜索 FAQ",
      "report-issue": "正在提交反馈",
      reportIssue: "正在提交反馈",
      "plan-visit-order": "正在安排游览顺序",
      planVisitOrder: "正在安排游览顺序",
    },
  },
};

const ja: UiCopy = {
  app: {
    title: "済州複合ルート案内",
    subtitle: "観光・グルメ・駐車場・充電器 12,368件を収録",
    chats: "会話一覧",
    routes: "保存したルート",
    newChat: "新しい会話",
    settings: "マイ情報",
    empty: "何をお手伝いしましょうか？",
    placeholder: "何でも聞いてください",
    listening: "聞いています… 終わったらマイクを再度タップ",
    send: "送信",
    stop: "停止",
    copy: "コピー",
    copied: "コピー済み",
    edit: "編集",
    cancel: "キャンセル",
    like: "いいね",
    dislike: "よくない",
    saveRoute: (n) => `このルートを保存（${n}箇所）`,
    savedRoute: "保存したルートを見る",
    routeSaved: "ルートを保存しました。",
    routeSaveFail: "空き容量不足でルートを保存できませんでした。",
    thinking: "考え中",
    stopping: "停止中",
    truncating: "前の回答を削除中",
    attachPhoto: "写真を添付",
    photoLimit: (n) => `写真は一度に${n}枚まで送れます。`,
    photoLimitPartial: (n) => `上限のため${n}枚だけ添付しました。`,
    feedbackThanks: "ご意見ありがとうございます。",
    feedbackFail: "送信に失敗しました。しばらくしてから再度お試しください。",
    retractFail: "サーバー履歴を整理できず、質問を残しました。",
    editMeta: "送信するとこの質問以降の会話は消え、新しい回答になります。",
    editMetaPhotos: (n) => ` 添付写真${n}枚も一緒に送ります。`,
    stopped: "回答を停止しました",
    reasonTitle: "どの点が不満でしたか？（任意）",
    reasonPlaceholder: "詳しく書いていただけると改善に役立ちます",
    close: "閉じる",
    reasons: ["情報が違う", "質問と合わない", "長すぎる／複雑", "場所が見つからない"],
    missingKey:
      "VITE_API_KEY が設定されていません。\nchat/web/.env.local.example を .env.local にコピーしてキーを入れ、\ndev サーバーを再起動してください。",
  },
  suggestions: [
    "済州空港から東門市場への行き方を比べて",
    "バスとタクシーで城山日出峰へ行く方法",
    "明日の天気に合うプラン",
    "車いすで済州市庁へ行くルート",
    "車なしで挟才海水浴場へ一番早く行く方法",
  ],
  weatherSuggestionIndex: 2,
  profile: {
    title: "マイ情報",
    desc1: "このブラウザにのみ保存され、おすすめに使います。空欄でも構いません。",
    desc2: "あとからマイ情報で変更できます。",
    later: "あとで",
    save: "保存して始める",
    language: "言語",
    otherLangHint: "一覧にない言語は英語で表示されます",
    nationality: "国籍",
    nationalityPlaceholder: "選択してください",
    nationalityClear: "国籍の選択を解除",
    nationalityEmpty: "検索結果がありません",
    ageGroup: "年代",
    transport: "移動手段",
    transportHint: "当てはまるものをすべて選択",
    fuel: "車両燃料",
    chargePorts: "充電ポート（複数可）",
    parkingPrivilege: "駐車優遇",
    parkingPrivilegeHint: "該当する減免・専用枠を選択（複数可 · EVは燃料で選択）",
    travelTypes: "旅行タイプ",
    travelHint: "興味のあるものを選択（複数可）",
    valuePref: "消費タイプ",
    valueForMoney: "コスパ",
    valueHeart: "ココロコスパ",
    valueFlex: "flex",
    placePref: "屋内 / 屋外",
    indoor: "屋内寄り",
    mid: "中間",
    outdoor: "屋外寄り",
    access: "バリアフリー",
    accessHint: "必要なバリアフリー種別（複数可）",
    diet: "食事",
    dietHint: "ベジ・小麦・ハラール・関連疾患など",
    vegNone: "ベジ該当なし",
    wheatFree: "小麦制限",
    conditionHint: "食事関連の疾患（複数可 · 病名のみ保存）",
    allergyHint: "アレルギー（韓国食薬処表示19種・複数可）",
    transports: {
      walk: "徒歩",
      taxi: "タクシー",
      bus: "バス",
      car: "車",
      shared_bike: "シェアキックボード/自転車",
    },
    fuels: { gasoline_diesel: "ガソリン/ディーゼル", lpg: "LPG", ev: "EV" },
    charges: {
      dc_combo: "DCコンボ",
      ac_slow: "普通充電",
      nacs: "NACS",
      ac_3phase: "AC三相",
      dc_chademo: "チャデモ",
    },
    parkingPrivileges: {
      compact: "軽自動車",
      disabled: "障害者",
      veteran: "国家功労者",
      pregnant: "妊婦",
      multi_child: "多子女",
    },
    travels: {
      food: "グルメ",
      shopping: "ショッピング",
      experience: "体験",
      culture: "文化・歴史",
      nature: "自然・休養",
    },
    accessOpts: {
      infant: { label: "乳幼児", hint: "ベビーカー・授乳室・子供椅子など" },
      pet: { label: "ペット", hint: "ペット同伴可の場所" },
      mobility: { label: "肢体", hint: "駐車・車椅子・エレベーターなど" },
      visual: { label: "視覚", hint: "点字・案内・音声ガイドなど" },
      hearing: { label: "聴覚", hint: "手話・字幕など" },
    },
    veg: { flexitarian: "フレキシタリアン", lacto_ovo: "ラクトオボ", vegan: "ヴィーガン" },
    conditions: {
      diabetes: "糖尿病",
      hypertension: "高血圧",
      kidney: "腎臓疾患",
      hyperlipidemia: "高脂血症",
      gout: "痛風",
      fatty_liver: "脂肪肝",
    },
    allergies: {
      egg: "卵類",
      milk: "牛乳",
      buckwheat: "そば",
      peanut: "ピーナッツ",
      soy: "大豆",
      wheat: "小麦",
      mackerel: "サバ",
      crab: "カニ",
      shrimp: "エビ",
      pork: "豚肉",
      peach: "桃",
      tomato: "トマト",
      sulfite: "亜硫酸塩",
      walnut: "くるみ",
      chicken: "鶏肉",
      beef: "牛肉",
      squid: "イカ",
      shellfish: "貝類（カキ・アワビ・ムール）",
      pine_nut: "松の実",
    },
    nationalities: {
      KR: "韓国",
      CN: "中国",
      JP: "日本",
      TW: "台湾",
      HK: "香港",
      US: "アメリカ",
      SG: "シンガポール",
      TH: "タイ",
      VN: "ベトナム",
      MY: "マレーシア",
      ID: "インドネシア",
      PH: "フィリピン",
      GB: "イギリス",
      DE: "ドイツ",
      FR: "フランス",
      AU: "オーストラリア",
      CA: "カナダ",
      RU: "ロシア",
      IN: "インド",
      MN: "モンゴル",
      OTHER: "その他",
    },
    ageGroups: {
      "10s": "10代",
      "20s": "20代",
      "30s": "30代",
      "40s": "40代",
      "50s": "50代",
      "60plus": "60+",
    },
    languages: { ko: "한국어", zh: "中文", en: "English", ja: "日本語", other: "その他" },
  },
  library: {
    label: "ライブラリ",
    chats: "会話",
    routes: "保存したルート",
    close: "閉じる",
    note: "このブラウザにのみ保存されます。サイトデータを消すとなくなります。",
    emptyRoutes: "保存したルートはありません。",
    emptyFavoriteRoutes: "お気に入りのルートはありません。",
    allRoutes: "すべて",
    favoriteRoutes: "お気に入り",
    addFavorite: "お気に入りに追加",
    removeFavorite: "お気に入りを解除",
    showOnMap: "地図で見る",
    emptyChats: "会話はありません。",
    search: "検索",
    delete: "削除",
    export: "書き出し",
    rename: "名前変更",
    use: "使う",
    openChat: "会話を開く",
  },
  mode: { candidate: "候補選び", route: "ルート", faq: "FAQ", report: "報告" },
  tool: {
    thinking: "考え中",
    running: (name) => `${name} 実行中`,
    labels: {
      "kakao-search-places": "Kakaoマップで場所を検索中",
      kakaoSearchPlaces: "Kakaoマップで場所を検索中",
      "kakao-directions": "Kakao経路を取得中",
      kakaoDirections: "Kakao経路を取得中",
      "compare-directions": "移動手段の経路を比較中",
      compareDirections: "移動手段の経路を比較中",
      "search-places": "場所を検索中",
      searchPlaces: "場所を検索中",
      "search-downtown-stores": "原都心の店舗を検索中",
      searchDowntownStores: "原都心の店舗を検索中",
      "nearby-places": "周辺を確認中",
      nearbyPlaces: "周辺を確認中",
      "place-detail": "詳細を確認中",
      placeDetail: "詳細を確認中",
      "check-metric": "混雑・空きを確認中",
      checkMetric: "混雑・空きを確認中",
      "get-weather": "天気を確認中",
      getWeather: "天気を確認中",
      "naver-map-link": "地図リンクを作成中",
      naverMapLink: "地図リンクを作成中",
      "search-faq": "FAQを検索中",
      searchFaq: "FAQを検索中",
      "report-issue": "報告を受付中",
      reportIssue: "報告を受付中",
      "plan-visit-order": "訪問順を作成中",
      planVisitOrder: "訪問順を作成中",
    },
  },
};

export const UI_COPY: Record<AppLocale, UiCopy> = { ko, en, zh, ja };
